config/routes.rb
Rails.application.routes.draw do
  get 'projects/matches'
  devise_for :users
  root to: 'pages#home'

  resources :projects do
    resources :matches, only: %I[create destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :matches, dependent: :destroy
  has_many :participants, through: :matches, source: :user #jointure

  validates :title, presence: true
  validates :description, presence: true
  validates :tag1, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :email, presence: true
  validates :profession, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def create
    @match = Match.new
    @match.user_id = current_user.id
    @project = Project.find(params[:project_id])
    @match.project = @project
    if @match.save
      flash[:success_modal] = "You have successfully registered!"
      redirect_to project_path(@project)
    else
      render "project/show"
    end
  end

  def destroy
    @match = Match.find_by('user_id= ? AND project_id =?', current_user.id, params[:id])
    @project = Project.find(params[:project_id])
    redirect_to projects_path if @match.destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        title ILIKE :query \
        OR tag1 ILIKE :query \
        OR tag2 ILIKE :query \
        OR tag3 ILIKE :query \
      "
      @projects = Project.all.where(sql_query, query: "%#{params[:query]}%")
    else
      @projects = Project.includes(:user)
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save!
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.user == current_user
      @project.destroy!
    end
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :tag1, :tag2, :tag3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scopp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/projects/index.html.erb
<div class="searchBar">
  <%= form_tag projects_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a project"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>


<div class="container">
  <h1>Projects</h1>
  <div class="card-group">
    <div class="card-orga">
      <% @projects.each do |p| %>
      <div class="card text-center">
        <div class="card-body d-flex flex-column">
          <h3 class="P-title"><%= p.title %></h3>
          <p id="Owner">Lead: <%= p.user.username %></p>
          <div class="d-flex justify-content-between mt-auto align-items-center">
            <div><%= p.participants.count %> Participants</div>
            <%= link_to "Go", project_path(p), class:"btn-success go"%>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
  <div class="fixed-bottom text-center">
    <%= link_to "Add a project", new_project_path , class:"btn btn-create"%>
  </div>

app/views/projects/new.html.erb
<div class="dflex align-center container">
  <h1>Create a new project</h1>
  <%= simple_form_for(@project) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :tag1, label: "Tag 1" %><%= f.input :tag2, label: "Tag 2" %><%= f.input :tag3, label: "Tag 3" %>
  <div class="submit">
  <%= f.submit %>
  </div>
  <% end %>



  </div>

app/views/projects/show.html.erb
<div class="container">
  <div class="card">
    <h1><%= @project.title %></h1>
      <div class="creator">
        Created by : <%= @project.user.username %>
      </div>
    <div class="tags"><%= @project.tag1 %> / <%= @project.tag2 %> / <%= @project.tag3 %></div>
    <div class="description">
      <%= @project.description %>
      <div class="participants">
        <h3>Participants</h3>
        <div>
          <% @project.participants.each do |user| %>
          <div>
            •<%= user.username || user.email %>
          </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="cont-btn">
    <%= link_to "Go back", projects_path, class:'btn btn-primary'%>
    <div>
      <div class="btn btn-success">
        <%= link_to "Participate", project_matches_path(@project.id), method: :post unless @project.user == current_user%>
      </div>
      <% if @project.user == current_user %>
      <%= link_to "Delete Project", project_path(@project), method: :delete, class:'btn btn-alert'%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<head>
  <style>
  @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Roboto:wght@100;400&display=swap');
  </style>
</head>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to projects_path, class: "navbar-brand" do %>
    <%= image_tag "teamwork.png" %>
  <% end %>

  <h1 style= "font-family:">Scopp</h1>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>